### ISSUE TITLE
ERR_CONNECTION_REFUSED for bundle.js and sample.ico

### ISSUE THREAD

**Issue by cassmtnr** [Kiosked/react-redux-boilerplate#1]
Having error of `ERR_CONNECTION_REFUSED` for `bundle.js` and `sample.ico` because `webpack.config.js` had baseURL as `http://localhost/` instead of `http://localhost + port`. Wonder if it was on purpose.

**Comment by cassmtnr** [comment]
Could fix baseURL for `http://localhost:3000` and add `"serve": "serve -p 3000 ./dist"` on package.json to fix this issue if it's not on purpose.

Fixed it on the commit to my fork (https://github.com/cassianomon/react-redux-boilerplate/commit/0048235d6a40b028dcad67e150a14332253f9a83), if you want me to create pull just tell me. if it's not a issue you can close this.

PS: I am starting to study React, it is a very good boilerplate to start, thanks!

**Comment by perry-mitchell** [comment]
@cassianomon Yes we must've been just hosting it on port 80 during some testing, apologies for missing that.

We'd definitely accept a PR for your fix!

**Comment by perry-mitchell** [comment]
> PS: I am starting to study React, it is a very good boilerplate to start, thanks!

Happy you like it! We love react+redux.. Our apps have never been this clear and concise :grin:
